name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Pobranie repozytorium
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalacja Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Instalacja zależności
      - name: Install dependencies
        run: npm install

      # Lintowanie kodu
      - name: Lint code
        run: npm run lint

      # Testowanie
      - name: Run tests
        run: npm test

      # Generowanie dokumentacji
      - name: Generate documentation
        run: npm run generate-docs

      # Commit i push automatycznie zaktualizowanej dokumentacji
      - name: Commit Documentation
        if: steps.generate-documentation.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Automatyczna aktualizacja dokumentacji" || echo "Brak zmian do commitowania"
          git push
